files:  
  - source: src/Mod/Sketcher/Gui/Resources/translations/Sketcher.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /SketcherLink.ts
    escape_quotes: 0
    escape_special_characters: 0
