pull_request_title: '[skip ci] Crowdin upload'
pull_request_labels:
  - crowdin
  - l10n
files:
  - source: src/Mod/AddonManager/Resources/translations/AddonManager.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /AddonManagerRT.ts
  - source: src/Gui/Language/FreeCAD.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /FreeCADRT.ts
  - source: src/Mod/PartDesign/Gui/Resources/translations/PartDesign.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /PartDesignRT.ts
  - source: src/Mod/Part/Gui/Resources/translations/Part.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /PartRT.ts
  - source: src/Mod/Path/Gui/Resources/translations/Path.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /PathRT.ts
  - source: src/Mod/Sketcher/Gui/Resources/translations/Sketcher.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /SketcherRT.ts
  - source: src/Mod/Spreadsheet/Gui/Resources/translations/Spreadsheet.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /SpreadsheetRT.ts
  - source: src/Mod/Start/Gui/Resources/translations/StartPage.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /StartPageRT.ts
  - source: src/Mod/TechDraw/Gui/Resources/translations/TechDraw.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /TechDrawRT.ts
  - source: src/Mod/Web/Gui/Resources/translations/Web.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /WebRT.ts    
